#!/usr/bin/env bash
#
# Build the upstream C library and compare the Fortran port with it
# (compare/), writing compare/RESULTS.md, or printing a short report with
# "quick" (used by CI).
#
# Two runs:
#  1. accuracy, bit for bit: both built with -O2 -ffp-contract=off (no fused
#     multiply-adds, which the two compilers would form differently), so that
#     the port and the C code round identically;
#  2. accuracy and speed with the optimized builds (CFLAGS, FFLAGS).
#
# Usage: tools/run_compare.sh [quick]   (from the repository root)
#
# Environment variables: CC (see build_upstream.sh), CFLAGS (default: -O3),
# FFLAGS (default: -O3 -funroll-loops: gfortran does not unroll at -O3, as
# clang and gcc do).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="${1:-full}"
CFLAGS_OPT="${CFLAGS:--O3}"
FFLAGS_OPT="${FFLAGS:--O3 -funroll-loops}"
EXACT="-O2 -ffp-contract=off"

run() { # $1: C flags, $2: Fortran flags, $3: mode of the driver, $4: output
    CFLAGS="$1" "$ROOT/tools/build_upstream.sh" > /dev/null
    cp "$ROOT/build/upstream/build_info.txt" "$4.info"
    (cd "$ROOT/compare" && fpm run --flag "$2" --link-flag "-L../build/upstream -ldaqp" -- "$3") > "$4"
}

env_table() { # $1: build_info.txt, $2: Fortran flags
    echo "| | |"
    echo "|---|---|"
    while IFS= read -r line; do
        echo "| ${line%%:*} | ${line#*: } |"
    done < "$1"
    echo "| Fortran compiler | $(gfortran --version | head -1) |"
    echo "| Fortran flags | $2 |"
    echo "| machine | $(uname -sm) $( (sysctl -n machdep.cpu.brand_string 2>/dev/null || grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2) | xargs) |"
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if [ "$MODE" = "quick" ]; then
    run "$EXACT" "$EXACT" accuracy "$TMP/exact"
    run "$CFLAGS_OPT" "$FFLAGS_OPT" quick "$TMP/opt"
else
    run "$EXACT" "$EXACT" accuracy "$TMP/exact"
    run "$CFLAGS_OPT" "$FFLAGS_OPT" full "$TMP/opt"
fi

{
    echo "# Comparison with upstream DAQP"
    echo
    echo "Generated by \`tools/run_compare.sh\` on $(date -u +%Y-%m-%d)."
    echo
    echo "# 1. Bit for bit (no fused multiply-adds)"
    echo
    env_table "$TMP/exact.info" "$EXACT"
    echo
    cat "$TMP/exact"
    echo
    echo "# 2. Optimized builds"
    echo
    env_table "$TMP/opt.info" "$FFLAGS_OPT"
    echo
    cat "$TMP/opt"
} > "$TMP/report.md"

if [ "$MODE" = "quick" ]; then
    cat "$TMP/report.md"
    # fail if any accuracy row has a count below the number of problems
    if awk -F'|' '/^\| [0-9][a-z]?\. /{for(i=4;i<=11;i++) if($i+0 < $3+0 && i!=4) bad=1} END{exit !bad}' "$TMP/report.md"; then
        echo "comparison: FAILED" >&2
        exit 1
    fi
    echo "comparison: passed" >&2
else
    mv "$TMP/report.md" "$ROOT/compare/RESULTS.md"
    echo "wrote compare/RESULTS.md"
fi
